workflows:
  ios-workflow:
    name: iOS Release
    environment:
      vars:
        BUNDLE_ID: "com.example.myapp"
      flutter: "stable"
      xcode: "latest"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      provisioning_profiles:
        com.example.myapp: My_Provisioning_Profile.mobileprovision
      certificates:
        - certificate.p12